# Generated by Django 4.1.5 on 2024-10-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegSHOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_list', models.CharField(max_length=100)),
                ('security_name', models.CharField(max_length=100)),
                ('added_last_10_days', models.TextField()),
                ('deleted_last_10_days', models.TextField()),
            ],
        ),
    ]
