# Generated by Django 4.1.5 on 2024-10-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_regshodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeMonthsShortVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=10)),
                ('short_volume', models.FloatField()),
                ('short_exempt_volume', models.FloatField()),
                ('total_volume', models.FloatField()),
                ('market', models.CharField(max_length=50)),
            ],
        ),
    ]
