# Generated by Django 4.1.5 on 2024-10-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_threemonthsshortvolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeMonthsRegSHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=20)),
                ('security_name', models.CharField(blank=True, max_length=255, null=True)),
                ('market_category', models.CharField(blank=True, max_length=1, null=True)),
                ('reg_sho_threshold_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('rule_3210', models.CharField(blank=True, max_length=1, null=True)),
                ('filler', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
