# Generated by Django 4.1.5 on 2024-10-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_threemonthsregsho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegSHOData',
        ),
        migrations.DeleteModel(
            name='ShortVolume',
        ),
        migrations.RenameField(
            model_name='threemonthsshortvolume',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='threemonthsshortvolume',
            old_name='market',
            new_name='Market',
        ),
        migrations.RenameField(
            model_name='threemonthsshortvolume',
            old_name='short_exempt_volume',
            new_name='ShortExemptVolume',
        ),
        migrations.RenameField(
            model_name='threemonthsshortvolume',
            old_name='short_volume',
            new_name='ShortVolume',
        ),
        migrations.RenameField(
            model_name='threemonthsshortvolume',
            old_name='symbol',
            new_name='Symbol',
        ),
        migrations.RenameField(
            model_name='threemonthsshortvolume',
            old_name='total_volume',
            new_name='TotalVolume',
        ),
    ]
