# Generated by Django 4.1.5 on 2024-10-28 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_delete_regshodata_delete_shortvolume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threemonthsregsho',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='threemonthsregsho',
            old_name='symbol',
            new_name='Symbol',
        ),
    ]
