# Generated by Django 4.1.5 on 2024-11-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_rename_date_threemonthsregsho_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SECData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('form_type', models.CharField(max_length=50)),
                ('form_description', models.TextField()),
                ('filing_date', models.DateField()),
                ('report_date', models.DateField(blank=True, null=True)),
                ('filing_href', models.URLField()),
                ('document_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'filing_date', 'form_type')},
            },
        ),
    ]
