# Generated by Django 4.1.5 on 2024-12-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_daystocksymbolinfo_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('ratio', models.CharField(max_length=20)),
            ],
        ),
    ]
