# Generated by Django 4.1.5 on 2024-12-09 16:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0008_tickersplit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(default='Unknown Name', max_length=255)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('fill_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_type', models.CharField(choices=[('B', 'B'), ('S', 'S'), ('O', 'O')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
