# Generated by Django 4.1.5 on 2024-11-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_symbol_alter_secdata_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secdata',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Symbol',
        ),
    ]
