# Generated by Django 4.1.5 on 2024-11-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_symbol_alter_secdata_symbol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secdata',
            unique_together=set(),
        ),
    ]
