# Generated by Django 4.1.5 on 2024-11-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_alter_secdata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
