# Generated by Django 4.1.5 on 2024-11-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_alter_secdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secdata',
            name='filing_date',
            field=models.DateField(null=True),
        ),
    ]
