# Generated by Django 4.1.5 on 2024-11-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_alter_secdata_filing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secdata',
            name='filing_href',
            field=models.URLField(blank=True, null=True),
        ),
    ]
