# Generated by Django 4.1.5 on 2024-11-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_alter_secdata_filing_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secdata',
            name='report_date',
        ),
    ]
