# Generated by Django 4.1.5 on 2024-11-16 20:50

import analysis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0015_remove_secdata_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(default=analysis.models.get_default_superuser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'order'],
                'unique_together': {('user', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WatchListSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('watch_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='analysis.watchlist')),
            ],
        ),
    ]
