# Generated by Django 4.1.5 on 2024-11-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_watchlist_watchlistsymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
