# Generated by Django 4.1.5 on 2024-11-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_stockpricedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricedata',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
