# Generated by Django 4.1.5 on 2024-11-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_alter_stockpricedata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSymbolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('NewsTitle', models.CharField(max_length=255)),
                ('NewsLink', models.URLField()),
                ('providerPublishTime', models.DateTimeField()),
                ('news_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_data', to='analysis.newssymboldata')),
            ],
        ),
    ]
