# Generated by Django 4.1.5 on 2024-11-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_newssymboldata_newsdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockpricedata',
            options={'ordering': ['timestamp']},
        ),
    ]
