# Generated by Django 4.1.5 on 2024-11-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_alter_stockpricedata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsdata',
            options={'ordering': ['-Date']},
        ),
    ]
