# Generated by Django 4.1.5 on 2024-11-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0023_alter_newsdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newssymboldata',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterModelOptions(
            name='stocksymboldata',
            options={'ordering': ['symbol']},
        ),
    ]
