# Generated by Django 4.1.5 on 2024-11-23 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_grandstocksymboldata_grandstockpricenewssecdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
