# Generated by Django 4.1.5 on 2024-11-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0026_grandstocksymboldata_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='averageVolume10days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='averageVolume3months',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='dateShortInterest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='fiftyDayAverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='fiftyTwoWeekHigh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='fiftyTwoWeekLow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='floatShares',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='heldPercentInsiders',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='heldPercentInstitutions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='lastSplitDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='lastSplitFactor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='marketCap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='net_income',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='sharesOutstanding',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='sharesShort',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='sharesShortPreviousMonthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='sharesShortPriorMonth',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='shortPercentOfFloat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='total_assets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='total_equity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='total_liabilities',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grandstocksymboldata',
            name='total_revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
