# Generated by Django 4.1.5 on 2024-11-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0027_grandstocksymboldata_averagevolume10days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grandstockpricenewssecdata',
            options={'ordering': ['-Date']},
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='adj_close',
            new_name='Adj_Close',
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='close',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='timestamp',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='high',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='low',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='open',
            new_name='Open',
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='volume',
            new_name='Volume',
        ),
    ]
