# Generated by Django 4.1.5 on 2024-11-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0028_alter_grandstockpricenewssecdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grandstockpricenewssecdata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='Adj_Close',
            new_name='adj_close',
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='Close',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='High',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='Low',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='Open',
            new_name='open',
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='Date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='grandstockpricenewssecdata',
            old_name='Volume',
            new_name='volume',
        ),
    ]
