# Generated by Django 4.1.5 on 2024-11-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0030_alter_grandstockpricenewssecdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('custom_text', models.TextField(unique=True)),
                ('averageVolume3months', models.FloatField(blank=True, null=True)),
                ('averageVolume10days', models.FloatField(blank=True, null=True)),
                ('marketCap', models.BigIntegerField(blank=True, null=True)),
                ('fiftyTwoWeekLow', models.FloatField(blank=True, null=True)),
                ('fiftyTwoWeekHigh', models.FloatField(blank=True, null=True)),
                ('fiftyDayAverage', models.FloatField(blank=True, null=True)),
                ('floatShares', models.FloatField(blank=True, null=True)),
                ('sharesOutstanding', models.BigIntegerField(blank=True, null=True)),
                ('sharesShort', models.BigIntegerField(blank=True, null=True)),
                ('sharesShortPriorMonth', models.BigIntegerField(blank=True, null=True)),
                ('sharesShortPreviousMonthDate', models.DateField(blank=True, null=True)),
                ('dateShortInterest', models.DateField(blank=True, null=True)),
                ('shortPercentOfFloat', models.FloatField(blank=True, null=True)),
                ('heldPercentInsiders', models.FloatField(blank=True, null=True)),
                ('heldPercentInstitutions', models.FloatField(blank=True, null=True)),
                ('lastSplitFactor', models.FloatField(blank=True, null=True)),
                ('lastSplitDate', models.DateField(blank=True, null=True)),
                ('total_revenue', models.BigIntegerField(blank=True, null=True)),
                ('net_income', models.BigIntegerField(blank=True, null=True)),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('total_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('total_equity', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.DeleteModel(
            name='GrandStockPriceNewsSecData',
        ),
        migrations.DeleteModel(
            name='GrandStockSymbolData',
        ),
    ]
