# Generated by Django 4.1.5 on 2024-11-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_stocksymbolinfo_delete_grandstockpricenewssecdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksymbolinfo',
            name='custom_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
