# Generated by Django 4.1.5 on 2024-11-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_alter_stocksymbolinfo_custom_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksymbolinfo',
            name='dateShortInterest',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stocksymbolinfo',
            name='lastSplitDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stocksymbolinfo',
            name='sharesShortPreviousMonthDate',
            field=models.DateField(),
        ),
    ]
