# Generated by Django 4.1.5 on 2024-11-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_alter_stocksymbolinfo_dateshortinterest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksymbolinfo',
            name='dateShortInterest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocksymbolinfo',
            name='lastSplitDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocksymbolinfo',
            name='sharesShortPreviousMonthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
