# Generated by Django 4.1.5 on 2024-11-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_alter_stocksymbolinfo_dateshortinterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksymbolinfo',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
