# Generated by Django 4.1.5 on 2024-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_stocksymbolinfo_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayStockSymbolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('previousClose', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('currentPrice', models.FloatField(blank=True, null=True)),
                ('dayLow', models.FloatField(blank=True, null=True)),
                ('dayHigh', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('averageVolume3months', models.FloatField(blank=True, null=True)),
                ('averageVolume10days', models.FloatField(blank=True, null=True)),
                ('marketCap', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
