# Generated by Django 4.1.5 on 2024-11-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0036_daystocksymbolinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricedata',
            name='ShortExemptVolume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='ShortVolume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
