# Generated by Django 4.1.5 on 2024-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_stockpricedata_shortexemptvolume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricedata',
            name='regSho',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
