# Generated by Django 4.1.5 on 2024-12-03 20:32

import analysis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayStockSymbolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('previousClose', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('currentPrice', models.FloatField(blank=True, null=True)),
                ('dayLow', models.FloatField(blank=True, null=True)),
                ('dayHigh', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('averageVolume3months', models.FloatField(blank=True, null=True)),
                ('averageVolume10days', models.FloatField(blank=True, null=True)),
                ('marketCap', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='NewsSymbolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockSymbolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockSymbolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('custom_text', models.TextField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('averageVolume3months', models.FloatField(blank=True, null=True)),
                ('averageVolume10days', models.FloatField(blank=True, null=True)),
                ('marketCap', models.BigIntegerField(blank=True, null=True)),
                ('fiftyTwoWeekLow', models.FloatField(blank=True, null=True)),
                ('fiftyTwoWeekHigh', models.FloatField(blank=True, null=True)),
                ('fiftyDayAverage', models.FloatField(blank=True, null=True)),
                ('floatShares', models.FloatField(blank=True, null=True)),
                ('sharesOutstanding', models.BigIntegerField(blank=True, null=True)),
                ('sharesShort', models.BigIntegerField(blank=True, null=True)),
                ('sharesShortPriorMonth', models.BigIntegerField(blank=True, null=True)),
                ('sharesShortPreviousMonthDate', models.DateField(blank=True, null=True)),
                ('dateShortInterest', models.DateField(blank=True, null=True)),
                ('shortPercentOfFloat', models.FloatField(blank=True, null=True)),
                ('heldPercentInsiders', models.FloatField(blank=True, null=True)),
                ('heldPercentInstitutions', models.FloatField(blank=True, null=True)),
                ('lastSplitFactor', models.FloatField(blank=True, null=True)),
                ('lastSplitDate', models.DateField(blank=True, null=True)),
                ('total_revenue', models.BigIntegerField(blank=True, null=True)),
                ('net_income', models.BigIntegerField(blank=True, null=True)),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('total_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('total_equity', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreeMonthsRegSHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Symbol', models.CharField(max_length=20)),
                ('security_name', models.CharField(blank=True, max_length=255, null=True)),
                ('market_category', models.CharField(blank=True, max_length=1, null=True)),
                ('reg_sho_threshold_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('rule_3210', models.CharField(blank=True, max_length=1, null=True)),
                ('filler', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreeMonthsShortVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Symbol', models.CharField(max_length=10)),
                ('ShortVolume', models.FloatField()),
                ('ShortExemptVolume', models.FloatField()),
                ('TotalVolume', models.FloatField()),
                ('Market', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(default=analysis.models.get_default_superuser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'order'],
                'unique_together': {('user', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WatchListSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('watch_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='analysis.watchlist')),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adj_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('ShortVolume', models.FloatField(blank=True, null=True)),
                ('ShortExemptVolume', models.FloatField(blank=True, null=True)),
                ('regSho', models.CharField(blank=True, max_length=10, null=True)),
                ('stock_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_data', to='analysis.stocksymboldata')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SECData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form_type', models.CharField(max_length=50)),
                ('form_description', models.TextField()),
                ('filing_date', models.DateField(null=True)),
                ('filing_href', models.URLField(blank=True, null=True)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='analysis.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('NewsTitle', models.CharField(max_length=255)),
                ('NewsLink', models.URLField()),
                ('providerPublishTime', models.DateTimeField()),
                ('news_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_data', to='analysis.newssymboldata')),
            ],
            options={
                'ordering': ['-Date'],
            },
        ),
    ]
