# Generated by Django 4.1.5 on 2024-12-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_threemonthsregsho_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threemonthsregsho',
            name='Date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='threemonthsregsho',
            name='Symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='threemonthsregsho',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='threemonthsregsho',
            name='market_category',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='threemonthsregsho',
            name='reg_sho_threshold_flag',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='threemonthsregsho',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='threemonthsshortvolume',
            name='Date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='threemonthsshortvolume',
            name='Market',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='threemonthsshortvolume',
            name='Symbol',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='threemonthsshortvolume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='threemonthsshortvolume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
