# Generated by Django 4.1.5 on 2024-12-05 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_watchlist_updated_at_watchlistsymbol_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='newssymboldata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newssymboldata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='stocksymboldata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksymboldata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='Date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='NewsTitle',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='providerPublishTime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='newssymboldata',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stockpricedata',
            name='timestamp',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stocksymboldata',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
