# Generated by Django 4.1.5 on 2024-12-05 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_newsdata_created_at_newsdata_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daystocksymbolinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daystocksymbolinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='stocksymbolinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksymbolinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='daystocksymbolinfo',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stocksymbolinfo',
            name='company_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stocksymbolinfo',
            name='dateShortInterest',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocksymbolinfo',
            name='lastSplitDate',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocksymbolinfo',
            name='sharesShortPreviousMonthDate',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocksymbolinfo',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
