# Generated by Django 4.1.5 on 2024-12-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_daystocksymbolinfo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daystocksymbolinfo',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
