# Generated by Django 4.1.5 on 2024-12-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_buynsell'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickersplit',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
