# Generated by Django 4.1.5 on 2024-12-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_buynsell_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynsell',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
