# Generated by Django 4.1.5 on 2026-03-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_buynsell_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('earnings_date', models.DateField(db_index=True)),
                ('event_name', models.CharField(choices=[('Q1', 'Q1 Earning'), ('Q2', 'Q2 Earning'), ('Q3', 'Q3 Earning'), ('Q4', 'Q4 Earning'), ('Others', 'Others')], default='Others', max_length=20)),
                ('eps_estimate', models.FloatField(blank=True, null=True)),
                ('reported_eps', models.FloatField(blank=True, null=True)),
                ('revenue_estimate_avg', models.FloatField(blank=True, null=True)),
                ('surprise_pct', models.FloatField(blank=True, null=True)),
                ('earning_call_time', models.CharField(choices=[('AMC', 'After Market Close'), ('BMO', 'Before Market Open'), ('Others', 'Others')], default='Others', max_length=20)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('averageVolume10days', models.BigIntegerField(blank=True, null=True)),
                ('averageVolume3months', models.BigIntegerField(blank=True, null=True)),
                ('marketCap', models.BigIntegerField(blank=True, null=True)),
                ('fiftyDayAverage', models.FloatField(blank=True, null=True)),
                ('fiftyTwoWeekLow', models.FloatField(blank=True, null=True)),
                ('fiftyTwoWeekHigh', models.FloatField(blank=True, null=True)),
                ('sharesOutstanding', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-earnings_date'],
                'unique_together': {('symbol', 'earnings_date')},
            },
        ),
    ]
