# Generated by Django 4.1.5 on 2026-03-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_earningsdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earningsdata',
            options={'ordering': ['symbol'], 'verbose_name': 'Earnings Data', 'verbose_name_plural': 'Earnings Data'},
        ),
        migrations.RenameField(
            model_name='earningsdata',
            old_name='earning_call_time',
            new_name='earning_call_time_1',
        ),
        migrations.RenameField(
            model_name='earningsdata',
            old_name='eps_estimate',
            new_name='eps_estimate_1',
        ),
        migrations.RenameField(
            model_name='earningsdata',
            old_name='reported_eps',
            new_name='eps_estimate_2',
        ),
        migrations.RenameField(
            model_name='earningsdata',
            old_name='revenue_estimate_avg',
            new_name='eps_estimate_3',
        ),
        migrations.RenameField(
            model_name='earningsdata',
            old_name='event_name',
            new_name='event_name_1',
        ),
        migrations.RenameField(
            model_name='earningsdata',
            old_name='surprise_pct',
            new_name='reported_eps_1',
        ),
        migrations.AlterUniqueTogether(
            name='earningsdata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='earning_call_time_2',
            field=models.CharField(choices=[('AMC', 'After Market Close'), ('BMO', 'Before Market Open'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='earning_call_time_3',
            field=models.CharField(choices=[('AMC', 'After Market Close'), ('BMO', 'Before Market Open'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='earning_call_time_4',
            field=models.CharField(choices=[('AMC', 'After Market Close'), ('BMO', 'Before Market Open'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='earnings_date_1',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='earnings_date_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='earnings_date_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='earnings_date_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='eps_estimate_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='event_name_2',
            field=models.CharField(choices=[('Q1', 'Q1 Earning'), ('Q2', 'Q2 Earning'), ('Q3', 'Q3 Earning'), ('Q4', 'Q4 Earning'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='event_name_3',
            field=models.CharField(choices=[('Q1', 'Q1 Earning'), ('Q2', 'Q2 Earning'), ('Q3', 'Q3 Earning'), ('Q4', 'Q4 Earning'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='event_name_4',
            field=models.CharField(choices=[('Q1', 'Q1 Earning'), ('Q2', 'Q2 Earning'), ('Q3', 'Q3 Earning'), ('Q4', 'Q4 Earning'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='reported_eps_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='reported_eps_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='reported_eps_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='revenue_estimate_avg_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='revenue_estimate_avg_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='revenue_estimate_avg_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='revenue_estimate_avg_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='surprise_pct_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='surprise_pct_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='surprise_pct_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsdata',
            name='surprise_pct_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earningsdata',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='earningsdata',
            name='earnings_date',
        ),
    ]
