# Generated by Django 4.1.5 on 2026-03-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_alter_earningsdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningsdata',
            name='earning_call_time_1',
            field=models.CharField(choices=[('AMC', 'AMC'), ('BMO', 'BMO'), ('DMT', 'DMT'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='earningsdata',
            name='earning_call_time_2',
            field=models.CharField(choices=[('AMC', 'AMC'), ('BMO', 'BMO'), ('DMT', 'DMT'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='earningsdata',
            name='earning_call_time_3',
            field=models.CharField(choices=[('AMC', 'AMC'), ('BMO', 'BMO'), ('DMT', 'DMT'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='earningsdata',
            name='earning_call_time_4',
            field=models.CharField(choices=[('AMC', 'AMC'), ('BMO', 'BMO'), ('DMT', 'DMT'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='earningsdata',
            name='event_name_1',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='earningsdata',
            name='event_name_2',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='earningsdata',
            name='event_name_3',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='earningsdata',
            name='event_name_4',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('Others', 'Others')], default='Others', max_length=20),
        ),
    ]
