# Generated by Django 4.1.5 on 2026-03-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_alter_earningsdata_earning_call_time_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP500Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'S&P 500 Ticker',
                'verbose_name_plural': 'S&P 500 Tickers',
                'ordering': ['symbol'],
            },
        ),
    ]
