# Generated by Django 4.1.5 on 2026-03-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_sp500ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningsdata',
            name='stock_index',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
